[tool.poetry]
name = "BB"
version = "0.00.0"
description = "d"
authors = ["wtfvoyo <63644879+wtfvoyo@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
